#!/bin/sh
#
# @name Generic Antenna Tracker SITL
# @type Antenna Tracker
# @class Rover
# @output Servo1 yaw servo
# @output Servo2 pitch servo
#

PX4_SIMULATOR=${PX4_SIMULATOR:=sihsim}

set VEHICLE_TYPE antenna_tracker

param set-default MAV_TYPE 5
param set-default EKF2_MAG_TYPE 1

# Enable simulated sensors for tracker SITL
param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1

param set-default COM_PREARM_MODE 2
param set-default COM_DISARM_LAND -1
param set-default COM_DISARM_PRFLT -1

# Tracker defaults
param set-default TRK_MODE 0
# Retained only for old parameter files. Tracker modes use TRK_MODE.
param set-default TRK_QGC_MODE 0
param set-default TRK_YAW_P 0.0
param set-default TRK_PIT_P 0.0
param set-default TRK_YAW_SLEW 2.0
param set-default TRK_PIT_SLEW 2.0
param set-default TRK_YAW_MIND -180.0
param set-default TRK_YAW_MAXD 180.0
param set-default TRK_YAW_PARK 0.0
param set-default TRK_PIT_MIND 0.0
param set-default TRK_PIT_MAXD 90.0
param set-default TRK_PIT_PARK 0.0
param set-default TRK_DEADRECK 0
param set-default TRK_AUTO_SCAN 0
param set-default TRK_ALT_SRC 0
param set-default TRK_DIST_MIN 5.0
param set-default TRK_SERVO_TEST 0

param set-default PWM_MAIN_FUNC1 201
param set-default PWM_MAIN_FUNC2 202

antenna_tracker start
