#!/bin/sh
#
# @name Generic Antenna Tracker SITL
# @type Antenna Tracker
# @class Rover
# @output Servo1 yaw servo
# @output Servo2 pitch servo
#

PX4_SIMULATOR=${PX4_SIMULATOR:=sihsim}

set VEHICLE_TYPE antenna_tracker

param set-default MAV_TYPE 5
param set-default EKF2_MAG_TYPE 1

# Enable simulated sensors for tracker SITL
param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1
# Model the tracker as a ground-supported pedestal. The default SIH quadrotor
# tumbles without multicopter controllers and falsely trips the roll/pitch
# failure detector when the tracker is armed.
param set-default SIH_VEHICLE_TYPE 5

param set-default COM_PREARM_MODE 2
param set-default COM_DISARM_LAND -1
param set-default COM_DISARM_PRFLT -1

# Tracker defaults
param set-default TRK_MODE 0
param set-default TRK_STRT_DLY 2.0
param set-default TRK_YAW_P 0.0
param set-default TRK_PIT_P 0.0
param set-default TRK_YAW_SLEW 2.0
param set-default TRK_PIT_SLEW 2.0
param set-default TRK_YAW_MIND -180.0
param set-default TRK_YAW_MAXD 180.0
param set-default TRK_YAW_PARK 0.0
param set-default TRK_PIT_MIND 0.0
param set-default TRK_PIT_MAXD 90.0
param set-default TRK_PIT_PARK 0.0
param set-default TRK_ALT_SRC 0
param set-default TRK_DIST_MIN 5.0

param set-default PWM_MAIN_FUNC1 201
param set-default PWM_MAIN_FUNC2 202

antenna_tracker start
